services:
  postgres:
    container_name: db_pg_sql
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - ms-net
    restart: unless-stopped

networks:
  ms-net:
    driver: bridge

volumes:
  postgres: