spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

server:
  port: 8052
